### ISSUE TITLE
Live Updating on scroll bug

### ISSUE THREAD

**Issue by dgmerek** [D-Programming-Man/Pseudo#10]
Currently when Live Update is enabled every action scrolling the input window will also update it. This might be an issue with the method for detecting updates being too broad but I'm not sure.

If we want this to be a feature feel free to close this issue.

**Comment by D-Programming-Man** [comment]
Yeah, I was thinking about this as well. A solution could be that we can get the length of the text in the input box and see if the sizes has changed between the 1 second interval of live updating. I'm going to push the change right now and closing the issue.
