### ISSUE TITLE
current gui.py does not open

### ISSUE THREAD

**Issue by dbarU** [D-Programming-Man/Pseudo#3]
After the current changes to gui.py it wont open for me.

**Comment by D-Programming-Man** [comment]
Can you link the most recent commit version that will work for you?

**Comment by dbarU** [comment]
0b4bbea94787bfc2ab38d4b657d5a2b85ab905cf is the last one that works. Steven mentioned it had to do with the interpreter I believe

**Comment by D-Programming-Man** [comment]
Closing Issue. The interpreter function is now linked to the GUI.
