### ISSUE TITLE
Copy-Paste bug

### ISSUE THREAD

**Issue by stresend** [D-Programming-Man/Pseudo#7]
Copy and pasting text into the pseudo causes a runtime error.

**Comment by D-Programming-Man** [comment]
It seems like we can still copy and paste, but it only show the error 1 time at the initial copy and paste.
https://stackoverflow.com/questions/7090346/tkinter-text-selection-get-error
Based on what the answer is saying, we can probably just ignore it for now.

**Comment by D-Programming-Man** [comment]
Messing around with the _proxy function in the CustomText class, if we try to do this:
```
    def _proxy(self, *args):
        # let the actual widget perform the requested action
        cmd = (self._orig,) + args
        result = ""
        try:
          result = self.tk.call(cmd)
        except:
          pass
```
The error message won't print and allows us to copy and paste code.
I'll consider writing this to the numbertext.py file after the situation with the highlighter problem is solved.
