### ISSUE TITLE
Making a pseudo into a comment and then turning it back into Pseudo code doesn't correct highlight

### ISSUE THREAD

**Issue by D-Programming-Man** [D-Programming-Man/Pseudo#9]
For example: Make a pseudo statement 
```
Create a variable named x with a value 1
```

Turn it into a comment, making the whole line green
```
# Create a variable named x with a value 1
```

Then turning it back into a pseudo code:
```
Create a variable named x with a value 1
```

But then the code statement is still highlighted green, even when translating
It only corrects its color when reloading the pseudo file.

**Comment by dgmerek** [comment]
The issue gets fixed by a simple ```text.remove_tag("tag", "1.0", tk.END)``` before starting to highlight everything, but when live updating it caused an awkward looking flash on the text with it changing so fast. 

Let me know if you would prefer it changed to act like that Andrew.

**Comment by D-Programming-Man** [comment]
In the highlighter function, if I were to rearrange the keywords dictionary so that the "#" and quote characters gets access first, eg:
```
      keywords = {"#": "string", '"': "string", "'": "string",
                    
                  "Variable": "datatype", "Number": "datatype", "Int ": "datatype", "Int)": "datatype",
                  "Int,": "datatype", "String": "datatype", "str": "datatype", "List": "datatype",
                  "Table": "datatype", "dict": "datatype", "Function": "datatype", "Object": "datatype",

                  "Create ": "keyword", "Display ": "keyword", "Add ": "keyword", "Subtract ": "keyword",
                  "Multiply ": "keyword", "Divide ": "keyword", "Store ": "keyword", "Print": "keyword",
                  "Define ": "keyword", "def ": "keyword", "Run ": "keyword", "If": "keyword", "Loop": "keyword",
                  "for": "keyword", "Compare": "keyword", "While": "keyword", 
                  "Import": "keyword",
                  
                  "%": "keyword", "Pycode": "keyword"
                  }
```
it seems to mitigate some of the flashing on the input box. But on the output box where the python code is written to seems to flash as well with the live update.

To answer your question, I think it would be best to add that code line back into the highlighter function.
I'll try to see if there is anything that can be done with the highlighting of the output box.
